DragonMinded/libdragon

include/rdp.h
src/rdp.c

I've tested rendering all sorts of triangles on the n64 hardware and they all appear to look correct. I had to add the blend fill mode since Left Major triangles for some reason wouldn't fill correctly in the primitive fill mode. I might eventually calculate more accurate XH/XM values but setting them both to the highest vertex X value seems to work just fine.

rdp non-shaded triangle

---

tools/build

I have tested the new toolchain in Arch Linux, and it seems to work fine.

Updated toolchain (GCC 5.1.0, Binutils 2.25, Newlib 2.2.0)

---

Makefile
examples/ctest/Makefile
examples/dfsdemo/Makefile
examples/mptest/Makefile
examples/mputest/Makefile
examples/spritemap/Makefile
examples/test/Makefile
examples/timers/Makefile
examples/vrutest/Makefile
examples/vtest/Makefile
tools/build

to $N64_INST/mips64-elf/{lib,include}.
Old project Makefiles incompatible, but can be trivially fixed
(see the "examples" folder).
This causes less issues when installing to /usr, since
MIPS/libdragon-related files will be installed in /usr/{lib,include} otherwise, 
where it can conflict with native libraries.

Improved directory structure by moving all MIPS libraries/includes

---

src/inthandler.S

Without this fix, newer versions of GAS will abort the compilation with the message `.../src/inthandler.S:238: Error: attempt to store non-zero value in section `.bss'`

Fix bss-related compile error in inthandler.S with newer GAS versions

---

tools/mkdfs/mkdfs.c

This enables the tool to be used on mac OS.

Replace malloc.h with stdlib.h in mkdfs.

---

examples/vtest/main.c
include/display.h
src/display.c

The 64-byte req comes from docs, two new high-res modes tested on NTSC hw.

High resolutions, alignment

---

src/display.c

REd from the official osViBlack function. Tested on NTSC. Could be exposed as
a separate function too, letting users black the screen at any time.
This differs from the VI control reg format being zero; that's a "no signal"
black, while this is a "signal" black.

Keep the screen black when clearing the buffers, to avoid displaying garbage

---

src/system.c

Newlib exit calls _exit after running atexit routines.

Newlib contains exit(), but not _exit. Fixes builds calling exit()

---

src/mempak.c

The mputest-example did't work for me. I've found this to be the reason. 
The base code is accessing the sector pointer as an uint8_t and is then comparing the data to the uint16_t checksum. Don't know how this could have been working.
This could be done nicer but I did a quick fix.
Greetings,
jago85

fixed 16 bit accesses to 8 bit buffer in __validate_header

---

include/rdp.h
src/rdp.c

from https://github.com/conker64/libdragon/blob/master/src/rdp.c
Before we had MIRROR_DISABLED / MIRROR_ENABLED to enable / disable mirroring when displaying past boundaries but no easy way to display past boundaries.
This removes `MIRROR_ENABLED` but adds `MIRROR_X`, MIRROR_Y` and `MIRROR_XY` to be passed on the `rdp_draw_texture*` function to actually mirror the sprite.
This is how I use it:
```c
void rdp_draw_sprite_with_texture(sprite_t *sp, int x, int y, mirror_t mirror)
{
rdp_enable_texture_copy();
rdp_sync(SYNC_PIPE);
rdp_load_texture(0, 0, mirror, sp);
rdp_draw_sprite(0, x, y, mirror);
}
```
@anacierdem @DragonMinded

add texture mirroring

---

include/n64sys.h

Parentheses were not balanced, leading to compilation errors.

Fix wrong parentheses in CachedAddr

---

CHANGELOG.md
README.md
index.js
package-lock.json
package.json
src/n64sys.c

Bump version
Add changelog
NPM improvements.
`libdragon install` now skips CI shecks.
Fix non-volatile asm - see https://gcc.gnu.org/onlinedocs/gcc-4.7.2/gcc/Extended-Asm.html
> An asm instruction without any output operands will be treated identically to a volatile asm instruction.

New release 1.3.15

---

tools/build

Currently, people following the `ucode/Makefile` pattern of using `objcopy` to create sections of RSP binary code can hit an annoying bug in which the RSP symbol is not aligned to a 16-byte boundary, as required by `load_ucode` / `load_data` to operate correctly the DMA engine.
There are many possible workaround for this (including adding one of the many `bin2h` tools to the whole toolchain) but it looks like binutils just added a feature to `objcopy`. This is extracted from the [2.33 release notes](https://sourceware.org/ml/binutils/2019-10/msg00103.html):
> * Add --set-section-alignment &lt;section-name&gt;=&lt;power-of-2-align&gt;
>      option to objcopy to allow the changing of section alignments.
So it seems that makefiles could be adjusted to use that option to force the RSP binary …

Upgrade binutils to fix RSP assembly alignment

---

include/ucode.S

The current value was a copy/paste error from previous line.

Fix vand opcode

---

include/ucode.S

When using a MIPS opcode not available on RSP, before the user would get:
```Error: unrecognized opcode 'swr_na'```
After this PR, the error is more clear:
```Error: swr is not supported by RSP```

Improve error message when using MIPS opcodes not available on RSP

---

include/ucode.S

The standard mfc2/mtc2 (as defined by MIPS architecture and GCC) do not allow to specify the "element" argument for the vector register. RSP allows that, by using unused space in the opcode.

Reimplement mtc2/mfc2 with the extended syntax allowed by RSP

---

include/tpak.h

GCC 10 changed the default to the stricter `-fno-common` which causes errors when multiple static variables with the same name is defined in multiple compilation units. This PR removes the unused `_gameboy_cartridge_header` variable from the `tpak.h` header file, which currently blocks building with the GCC 10 defaults.

Fix compilation issue with GCC 10 and -fno-common

---

tools/n64tool.c

This PR contains 3 commits with misc fixes to n64tool:
* A real bug: the check for odd sizes for byte-swapping or zero-padding was never triggering, because of missing parentheses. LLVM detected this as soon as I first compiled this file, and btw I was looking for this bug as I had hit it: it produced a non-working ROM for my application because the assets where not in the correct position because of missing padding.
* Two speed fixes, by doing less I/O calls, using larger chunks. This brings the total execution time for a 64Mb ROM through the docker container from 4 seconds to 0.8 seconds.

N64tool fixes

---

n64.ld

Currently, it was possible to create data sections whose size were not
a multiple of 4 bytes (for instance, by simply declaring global
variables in the correct order so that the last one was only 1 or 2
bytes long). This produced correct binaries, that were unable to boot
because the libdragon bootloader (entrypoint.S) assumes that the data
section is multiple of 4 bytes, so it would loop forever.
This commit fixes the problem by forcing a padding to all sections.
I used padding to multiple of 16 bytes on text section (because it was already aligned
to 16-bytes, so I assume it might be important), and multiple of 8 bytes
for all the others (4 bytes is possibly enough, but 8 bytes means that
even changing the bootloader to use DMA to copy the sections won't
break it, so I guess it's more …

n64.ld: force padding of text/data/bss/rodata sections

---

include/ucode.S

RSP vector load/store instructions have a signed 7-bit offset.
Currently, it was being handled as unsigned offset, so negative
numbers were not allowed. Now, they are correctly handled so it is
possible to write instructions such as "sqv $v00,0, -2,s0" which is
perfectly valid.

ucode.S: handle negative offsets in load/store instructions
